#!/bin/bash
# script that creates the initial sql.
# each nino executable checks for nino.sql in the current folder to execute as initial script before starting.
pwd=$(pwd)
out_file="$pwd/nino.sql"
echo "CREATING: $out_file ..."
echo "copy: init db sql"
cp "$pwd/transport/db_init.sql" "$out_file"

#add new line
echo "" >> "$out_file"

# write_db: "db_alias" "db_type" "db_connection_string"
write_db () {
   echo "add db: $1"
   echo "INSERT INTO nino_database (db_alias, db_type, db_connection_string) " >> "$out_file"
   echo "VALUES ('$1', '$2', '$3');" >> "$out_file"
}

# add test db to point to the current one
write_db "test" "postgres" "$NINO"

# write_request: "request_path" "response_name" "redirect_flag" "authorize_flag"
write_request () {
   echo "add request: $1"
   echo "INSERT INTO nino_request (request_path, response_name, redirect_flag, authorize_flag) " >> "$out_file"
   echo "VALUES ('$1', '$2', $3, $4);" >> "$out_file"
}

# write_response: "response_name" "response_mime_type" "execute_flag" "transpile_flag" "response_content_file"
write_response () {
   echo "add response: $1"
   echo "INSERT INTO nino_response (response_name, response_mime_type, execute_flag, transpile_flag, response_content) " >> "$out_file"
   echo -n "VALUES ('$1', '$2', $3, $4, '\x" >> "$out_file"
   hexdump -v -e '1/1 "%02x" ""' $5 >> "$out_file"
   echo "'::bytea);" >> "$out_file"
}

# write_portlet: "user_role", "portlet_menu", "portlet_index", "portlet_icon", "portlet_name"
write_portlet () {
   echo "add portlet: $2"
   echo "INSERT INTO nino_portlet (user_role, portlet_menu, portlet_index, portlet_icon, portlet_name) " >> "$out_file"
   echo "VALUES ('$1', '$2', $3, '$4', '$5');" >> "$out_file"
}

#add main nino execution loop code and default transpile code
write_response   "_main"                "application/javascript;charset=UTF-8"   true    false  "transport/_main.js"
write_response   "_transpile_dynamics"  "application/javascript;charset=UTF-8"   true    false  "transport/_transpile_dynamics.js"

#add nino libraries
write_response   "_log"                 "application/javascript;charset=UTF-8"   true    false  "transport/_log.js"
write_response   "_db"                  "application/javascript;charset=UTF-8"   true    false  "transport/_db.js"
write_response   "_jsqlx"               "application/javascript;charset=UTF-8"   true    false  "transport/_jsqlx.min.js"
write_response   "_fetch"               "application/javascript;charset=UTF-8"   true    false  "transport/_fetch.js"
write_response   "_notify"              "application/javascript;charset=UTF-8"   true    true   "transport/_notify.js"
write_response   "_nino"                "application/javascript;charset=UTF-8"   true    true   "transport/_nino.js"

#add global unauthorized resources
write_request   "favicon.ico"         "favicon.ico"             false   false
write_response  "favicon.ico"         "image/x-icon"            false   false    "transport/favicon.ico"



#add demo redirect
write_request   "google"        "http://www.google.com"   true    false

#add demo requests and responses
write_request    "demo"                   "demo.html"                        false   false
write_response   "demo.html"              "text/html;charset=UTF-8"          false   false  "transport/demo.html"
write_request    "demo_static.json"       "demo_static.json"                 false   false
write_response   "demo_static.json"       "application/json;charset=UTF-8"   false   false  "transport/demo_static.json"
write_request    "demo_dynamic.json"      "demo_dynamic.json"                false   false
write_response   "demo_dynamic.json"      "application/json;charset=UTF-8"   true    true   "transport/demo_dynamic_json.js"
write_request    "demo_test_servlet"      "demo_test_servlet"                false   false
write_response   "demo_test_servlet"      "text/html;charset=UTF-8"          true    false  "transport/demo_test_servlet.js"
write_request    "demo_notify_servlet"    "demo_notify_servlet"              false   false
write_response   "demo_notify_servlet"    "text/html;charset=UTF-8"          true    false  "transport/demo_notify_servlet.js"
write_request    "demo_jsqlx_servlet"     "demo_jsqlx_servlet"               false   false
write_response   "demo_jsqlx_servlet"     "text/html;charset=UTF-8"          true    false  "transport/demo_jsqlx_servlet.js"
write_request    "demo_db_servlet"        "demo_db_servlet"                  false   false
write_response   "demo_db_servlet"        "text/html;charset=UTF-8"          true    true   "transport/demo_db_servlet.js"
write_request    "demo_db_list"           "demo_db_list"                     false   false
write_response   "demo_db_list"           "text/html;charset=UTF-8"          true    true   "transport/demo_db_list.js"
write_request    "demo_fetch_servlet"     "demo_fetch_servlet"               false   false
write_response   "demo_fetch_servlet"     "application/json;charset=UTF-8"   true    true   "transport/demo_fetch_servlet.js"
write_request    "demo_fetch_binary_servlet" "demo_fetch_binary_servlet"     false   false
write_response   "demo_fetch_binary_servlet" "image/png"                     true    true   "transport/demo_fetch_binary_servlet.js"
write_request    "demo_fetch_response_servlet" "demo_fetch_response_servlet" false   false
write_response   "demo_fetch_response_servlet" "image/png"                   true    true   "transport/demo_fetch_response_servlet.js"

#add PORTAL code with login
write_request    "login"                "login.html"                             false   false
write_response   "login.html"           "text/html;charset=UTF-8"                false   false  "transport/login.html"
write_request    "portal_login"         "portal_login"                           false   false
write_response   "portal_login"         "text/html;charset=UTF-8"                true    true   "transport/portal_login.js"
write_request    "/"                    "portal_main"                            false   true
write_request    "index.html"           "portal_main"                            false   true
write_request    "portal"               "portal_main"                            false   true
write_response   "portal_main"          "text/html;charset=UTF-8"                true    true  "transport/portal_main.js"
write_request    "portal_rest"          "portal_rest"                            false   true
write_response   "portal_rest"          "application/json;charset=UTF-8"         true    true  "transport/portal_rest.js"
write_request    "portal.js"            "portal.js"                              false   false
write_response   "portal.js"            "application/javascript;charset=UTF-8"   false   false  "transport/portal.js"
write_request    "portal.css"           "portal.css"                             false   false
write_response   "portal.css"           "text/css;charset=UTF-8"                 false   false  "transport/portal.css"
write_request    "portlet_menu.js"      "portlet_menu.js"                        false   true
write_response   "portlet_menu.js"      "application/javascript;charset=UTF-8"   false   true   "transport/portlet_menu.js"
write_request    "portlet_about.js"     "portlet_about.js"                       false   true
write_response   "portlet_about.js"     "application/javascript;charset=UTF-8"   false   true   "transport/portlet_about.js"
write_request    "portlet_counter.js"   "portlet_counter.js"                     false   true
write_response   "portlet_counter.js"   "application/javascript;charset=UTF-8"   false   true   "transport/portlet_counter.js"

write_request    "portlet_admin_requests.js"   "portlet_admin_requests.js"            false   true
write_response   "portlet_admin_requests.js"   "application/javascript;charset=UTF-8" false   true   "transport/portlet_admin_requests.js"
write_request    "portlet_admin_responses.js"  "portlet_admin_responses.js"           false   true
write_response   "portlet_admin_responses.js"  "application/javascript;charset=UTF-8" false   true   "transport/portlet_admin_responses.js"

#add ide in react
# write_request    "ide"               "ide/index.html"                         false   false
# write_response   "ide/index.html"    "text/html;charset=UTF-8"                false   false  "transport/ide/index.html"
# write_request    "ide/ide.js"        "ide/ide.js"                             false   false
# write_response   "ide/ide.js"        "application/javascript;charset=UTF-8"   false   false  "transport/ide/ide.js"
# write_request    "ide/ide.css"       "ide/ide.css"                            false   false
# write_response   "ide/ide.css"       "text/css;charset=UTF-8"                 false   false  "transport/ide/ide.css"

# update lengths
echo "UPDATE nino_response SET response_content_length = length(response_content);" >> "$out_file"

write_portlet "portal"  "Home"                  0 "home"      "portlet_about.js"
write_portlet "demo"    "Demo/Counter"         10 "file-plus" "portlet_counter.js"
write_portlet "admin"   "Admin/Requests"      900 "log-in"    "portlet_admin_requests.js"
write_portlet "admin"   "Admin/Responses"     910 "log-out"   "portlet_admin_responses.js"
write_portlet "admin"   "Admin/Users"         920 "user"      "portlet_about.js"
write_portlet "admin"   "Admin/Roles"         930 "users"     "portlet_about.js"
write_portlet "admin"   "Admin/Portal"        940 "layout"    "portlet_about.js"
write_portlet "admin"   "Admin/Settings"      950 "settings"  "portlet_about.js"
write_portlet "admin"   "Admin/Databases"     960 "database"  "portlet_about.js"
write_portlet "admin"   "Admin/Schedules"     970 "clock"     "portlet_about.js"
write_portlet "admin"   "Admin/Transports"    980 "truck"     "portlet_about.js"

echo "...DONE"