[package]
name = "nino"
description = "Scalable JS Platform"
authors = ["ScaleFocus"]
version = "1.0.0"
edition = "2021"
license = "MIT"

[dependencies]
tokio = { version = "1.32.0", features = ["full"] }
deno_core = "0.197.0"
deno_runtime =  "0.121.0"
postgres = "0.19.5"
tokio-postgres = "0.7.8"
deadpool-postgres = "0.10.5"
async-std = "1.12.0"
http-types = "2.12.0"
async-h1 = "2.3.3"
serde = "1.0.183"
serde_v8 = "0.108.0"
async-channel = "1.9.0"
hyper = "0.14.24"
hyper-tls = "0.5.0"
chrono = "0.4.26"
bcrypt = "0.15.0"
hmac = "0.12.1"
jwt = "0.16.0"
sha2 = "0.10.7"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
