[package]
name = "nino"
description = "Scalable JS Platform"
authors = ["ScaleFocus"]
version = "1.0.0"
edition = "2021"
license = "MIT"

[dependencies]
tokio = { version = "1.29.1", features = ["full"] }
deno_runtime =  "0.121.0"
deno_core = "0.197.0"
postgres = "0.19.5"
tokio-postgres = "0.7.8"
deadpool-postgres = "0.10.5"
async-std = "1.12.0"
http-types = "2.12.0"
async-h1 = "2.3.3"
serde = "1.0.176"
serde_v8 = "0.108.0"
spmc = "0.3.0"
async-channel = "1.8.0"
hyper = "0.14.24"
chrono = "0.4.26"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
