[package]
name = "nino"
description = "Scalable JS Platform"
authors = ["ScaleFocus"]
version = "1.0.0"
edition = "2021"
license = "MIT"

[dependencies]
tokio = { version = "1.26.0", features = ["full"] }
deno_core = "0.173.0"
postgres = "0.19.4"
tokio-postgres = "0.7.7"
deadpool-postgres = "0.10.5"
async-std = "1.12.0"
http-types = "2.12.0"
async-h1 = "2.3.3"
serde = "1.0.154"
serde_v8 = "0.84.0"
spmc = "0.3.0"
async-channel = "1.8.0"
hyper = "0.14.24"

[profile.release]
strip = true
opt-level = "s"
lto = true
codegen-units = 1
