#!/bin/bash
# db start | stop

pwd=$(pwd)
if [ ! -f "./pg/bin/pg_ctl" ] 
then
    if [ -f "./pg/pg.jar" ] 
    then
        echo "postgres jar found" 
    else
        echo "Downloading postgress..."
        mkdir -p pg
        curl https://repo1.maven.org/maven2/io/zonky/test/postgres/embedded-postgres-binaries-linux-amd64/14.5.0/embedded-postgres-binaries-linux-amd64-14.5.0.jar \
        --output ./pg/pg.jar
    fi
   #exctract jar
   cd ./pg
   jar -xvf pg.jar
   7z x -aoa postgres-linux-x86_64.txz
   tar -xvf postgres-linux-x86_64.tar
   cd ..
fi
if [ ! -d "./pg/db" ] 
then
    "$pwd/pg/bin/initdb" "$pwd/pg/db"
fi
case "$1" in
    "start" | "stop" )
        "$pwd/pg/bin/pg_ctl" -D "$pwd/pg/db" -l logfile $1
        exit 0
        ;;
    *) # DEFAULT
        echo "Use start/stop parameter"
        exit 1
        ;;
esac

#./pg/bin/pg_ctl -D ./pg/db -l logfile $1