#!/bin/bash
# db start | stop

pwd=$(pwd)
version="16.1.0"

if [ ! -f "./pg/bin/pg_ctl" ] 
then
    if [ -f "./pg/pg.jar" ] 
    then
        echo "postgres jar found" 
    else
        platform="linux"
        name=$(uname)
        if [[ "$name" -eq "Darwin" ]]
        then
            platform="darwin"
        fi

        echo "Platform: $platform"
        echo "Version: $version"
        echo "Downloading postgress..."
        mkdir -p pg
        pgurl="https://repo1.maven.org/maven2/io/zonky/test/postgres/embedded-postgres-binaries-$platform-amd64/$version/embedded-postgres-binaries-$platform-amd64-$version.jar"
        echo "Downloading: $pgurl"
        curl  "$pgurl" --output ./pg/pg.jar
        if [ $? -ne 0 ] 
        then 
            exit 1
        fi
    fi
   #exctract jar
   cd ./pg
   jar -xvf pg.jar
   7zz x -aoa postgres-$platform-x86_64.txz
   tar -xvf postgres-$platform-x86_64.tar
   cd ..
fi
if [ ! -d "./pg/db" ] 
then
    "$pwd/pg/bin/initdb" "$pwd/pg/db"
fi
case "$1" in
    "start" | "stop" )
        "$pwd/pg/bin/pg_ctl" -D "$pwd/pg/db" -l logfile $1
        exit 0
        ;;
    *) # DEFAULT
        echo "Use start/stop parameter"
        exit 1
        ;;
esac

#./pg/bin/pg_ctl -D ./pg/db -l logfile $1
