[package]
name = "reqwest_test"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.39.1", features = ["full"] }
http-types = "2.12.0"
anyhow = "1.0.95"
async-std = "1.13.0"
async-h1 = "2.3.4"
